---
# --------------------------------

- name: "Update package cache and grab some packages"
  ansible.builtin.apt:
    name: "{{ tor_dependent_pkgs }}"
    update_cache: true
    state: present
  become: true
  tags: [ct-tor]

- name: "Add tor repo key"
  ansible.builtin.apt_key:
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    keyserver: keys.gnupg.net
    state: present
    validate_certs: true
  become: true
  tags: [ct-tor]

- name: "Add tor repository to APT"
  ansible.builtin.apt_repository:
    repo: "{{ item }} {{ ct_codename }} main"
    state: present
  with_items:
  - "deb http://deb.torproject.org/torproject.org"
  - "deb-src http://deb.torproject.org/torproject.org"
  become: true
  register: reg_repo_list
  tags: [ct-tor]

- name: "Update apt cache and install Tor"
  ansible.builtin.apt:
    name: "tor"
    state: present
    update_cache: "{{ reg_repo_list is changed }}"
  become: true
  tags: [ct-tor]

# --------------------------------

- name: "Set up directory for DirPort page"
  ansible.builtin.file:
    mode: 0755
    owner: "{{ tor_owner }}"
    path: /var/www/html
    state: directory
  become: true
  tags: [ct-tor]

- name: "Transfer landing page over"
  ansible.builtin.template:
    dest: /var/www/html/index.html
    mode: "0644"
    owner: "{{ tor_owner }}"
    src: index.html.j2
  tags: [ct-tor]

- name: "Render /etc/tor/torrc"
  ansible.builtin.template:
    dest: /etc/tor/torrc
    group: root
    mode: "0644"
    owner: root
    src: torrc.j2
  become: true
  tags: [ct-tor]

# --------------------------------
...
